export const imagePath = {
    intro1: require('../assets/images/intro_photo1.png'),
    intro2: require('../assets/images/intro_photo2.png'),
    intro3: require('../assets/images/intro_photo3.png'),
    logo: require('../assets/images/logo.png'),
    bg: require('../assets/images/bg.png'),
    flick: require('../assets/images/flick.png'),
    olivearrow: require('../assets/images/olivearrow.png'),
    camera: require('../assets/images/icons/camera_photo.png'),
    gallery: require('../assets/images/icons/gallery_photo.png'),
    flip_photo: require('../assets/images/icons/flip_photo.png'),
    addIcon: require('../assets/images/icons/add_icon.png'),
    leftArrow: require('../assets/images/icons/left-arrow.png'),
    closeIcon: require('../assets/images/icons/close_photo.png'),
    SavePhoto: require('../assets/images/icons/save_photo.png'),
    orientation: require('../assets/images/orientation.png'),
    play: require('../assets/images/play.png'),
    playIcon: require('../assets/images/playIcon.png'),
    playBtn: require('../assets/images/icons/playBtn.png'),
    training: require('../assets/images/icons/training.png'),
    galleryIcon: require('../assets/images/icons/galleryIcon.png'),
    icon: require('../assets/images/icons/icon.png'),
}